/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_aps_jni_NativeDB */

#ifndef _Included_cn_aps_jni_NativeDB
#define _Included_cn_aps_jni_NativeDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_aps_jni_NativeDB
 * Method:    connect
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_aps_jni_NativeDB_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_aps_jni_NativeDB
 * Method:    query
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_aps_jni_NativeDB_query
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
