server.port=8899
camunda.bpm.admin-user.id=camunda
camunda.bpm.admin-user.password=camunda
camunda.bpm.admin-user.first-name=admin
camunda.bpm.filter.create=All tasks
camunda.bpm.database.type=mysql
camunda.bpm.database.schema-update=true
camunda.bpm.auto-deployment-enabled=true
camunda.bpm.deployment-resource-pattern=classpath:/processes/*.bpmn