# Spring DataSource
# \u914D\u7F6EH2\u5185\u5B58\u6570\u636E\u5E93\u7684\u8FDE\u63A5\u4FE1\u606F
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=lishirui
spring.datasource.password=lishirui

# Spring JPA
# \u914D\u7F6EJPA/Hibernate\u7684\u76F8\u5173\u5C5E\u6027
# \u6307\u5B9A\u9488\u5BF9H2\u6570\u636E\u5E93\u7684\u65B9\u8A00
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# hbm2ddl\uFF08Hibernate aotu ddl\uFF09\u7B56\u7565\uFF0Cupdate\u8868\u793A\u542F\u52A8\u65F6\u68C0\u67E5\u5E76\u66F4\u65B0\u8868\u7ED3\u6784
spring.jpa.hibernate.ddl-auto=update
