<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.aps.boot</groupId>
        <artifactId>component</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>cn.aps.boot.logs</groupId>
    <artifactId>aps-logs-assembly</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>aps-logs-api</module>
        <module>aps-logs-core</module>
        <module>aps-log-spring-boot-starter</module>
        <module>aps-log-boot-demo</module>
        <module>aps-log-java-demo</module>
    </modules>

    <properties>

    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.aps.boot.logs</groupId>
                <artifactId>aps-logs-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.aps.boot.logs</groupId>
                <artifactId>aps-logs-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.aps.boot.logs</groupId>
                <artifactId>aps-logs-demo</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.aps.boot.logs</groupId>
                <artifactId>aps-log-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>